CREATE TABLE `music` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL DEFAULT '',
	`file_id` VARCHAR(255) NOT NULL,
	`genre` VARCHAR(255) NOT NULL DEFAULT 'game',
	`lang` VARCHAR(50) NOT NULL DEFAULT 'en',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
